"""
Ai PhotoFlow - Enterprise Cryptographic Licensing & Anti-Tamper Engine
Multi-layer protection against software cracking, database hacking, clock tampering, and unauthorized copying:

1. Hardware Machine Fingerprinting (CPU & Motherboard bound)
2. Cryptographic HMAC-SHA256 Signature for SQLite state (Detects manual DB edits / hacking)
3. Anti-Clock Rollback Detection (Prevents setting computer clock back to bypass expiry)
4. Mathematically Signed License Keys (Cannot be forged or generated by crackers)
5. Operational Enforcement Guard (Protects RAW/JPG Export & High-Speed Culling)
"""
import os
import json
import sqlite3
import hashlib
import hmac
import time
import subprocess
import uuid
import platform
from datetime import datetime, timedelta
from typing import Dict, Any, Optional, Tuple
from backend.db.database import get_connection

# Cryptographic Salt (Secret internal pepper for HMAC-SHA256 signature verification)
_SECURITY_PEPPER = b"APF_EnterpriseSecSalt_2026_@nil$harma_CoreEngine#9971xK"

# Master PIN for Anil Sharma administrative overrides
ADMIN_MASTER_PIN = "Anil@#140477"

# Standard Pricing
PRICING_CATALOG = {
    "INR": {
        "PRO": {"monthly": 1499, "yearly": 11999},
        "STUDIO": {"monthly": 2999, "yearly": 23999},
        "EVENT": {"single": 499}
    },
    "USD": {
        "PRO": {"monthly": 19, "yearly": 149},
        "STUDIO": {"monthly": 39, "yearly": 299},
        "EVENT": {"single": 7}
    }
}

class LicenseService:
    def __init__(self):
        self.machine_id = self.get_machine_fingerprint()
        self._init_secure_tables()

    @staticmethod
    def get_machine_fingerprint() -> str:
        """
        Extracts hardware-bound identifiers from Apple Silicon / Intel Motherboard / CPU.
        Returns a unique, immutable 16-character hardware signature.
        """
        raw_hw = ""
        try:
            if platform.system() == "Darwin":
                # macOS IOPlatformExpertDevice extraction
                cmd = "ioreg -d2 -c IOPlatformExpertDevice"
                output = subprocess.check_output(cmd, shell=True, timeout=2).decode(errors="ignore")
                for line in output.split("\n"):
                    if "IOPlatformUUID" in line or "IOPlatformSerialNumber" in line:
                        raw_hw += line.strip()
            elif platform.system() == "Windows":
                # Windows Computer System Product UUID
                try:
                    cmd = 'powershell -NoProfile -Command "(Get-CimInstance -ClassName Win32_ComputerSystemProduct).UUID"'
                    raw_hw = subprocess.check_output(cmd, shell=True, timeout=2).decode(errors="ignore").strip()
                except Exception:
                    try:
                        cmd = "wmic csproduct get uuid"
                        output = subprocess.check_output(cmd, shell=True, timeout=2).decode(errors="ignore")
                        for line in output.split("\n"):
                            line = line.strip()
                            if line and "UUID" not in line:
                                raw_hw = line
                                break
                    except Exception:
                        pass
        except Exception:
            pass

        if not raw_hw:
            # Cross-platform fallback using hardware MAC node and CPU info
            raw_hw = f"{uuid.getnode()}:{platform.node()}:{platform.machine()}:{platform.processor()}"

        h = hashlib.sha256(raw_hw.encode()).hexdigest()[:16].upper()
        return f"{h[:4]}-{h[4:8]}-{h[8:12]}-{h[12:16]}"

    def _compute_security_signature(self, plan_name: str, expires_at: Optional[str], is_vip: int, max_devices: int) -> str:
        """
        Generates an unforgeable HMAC-SHA256 signature for the license row.
        If a cracker edits the SQLite DB with a DB tool, this signature will fail!
        """
        payload = f"{self.machine_id}::{plan_name}::{expires_at or 'LIFETIME'}::{is_vip}::{max_devices}"
        return hmac.new(_SECURITY_PEPPER, payload.encode("utf-8"), hashlib.sha256).hexdigest()

    def _init_secure_tables(self):
        conn = get_connection()
        cursor = conn.cursor()

        # Secure License State Table
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS license_state (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            plan_name TEXT DEFAULT 'FREE_TRIAL',
            license_key TEXT DEFAULT '',
            status TEXT DEFAULT 'ACTIVE',
            is_vip INTEGER DEFAULT 0,
            user_name TEXT DEFAULT '',
            user_email TEXT DEFAULT '',
            max_devices INTEGER DEFAULT 1,
            machine_id TEXT DEFAULT '',
            security_signature TEXT DEFAULT '',
            last_known_ts INTEGER DEFAULT 0,
            trial_started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMP,
            activated_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)

        # Migration: Ensure all security columns exist if table was created in an older schema
        cursor.execute("PRAGMA table_info(license_state)")
        existing_cols = {col[1] for col in cursor.fetchall()}
        columns_to_add = [
            ("machine_id", "TEXT DEFAULT ''"),
            ("security_signature", "TEXT DEFAULT ''"),
            ("last_known_ts", "INTEGER DEFAULT 0"),
        ]
        for col_name, col_def in columns_to_add:
            if col_name not in existing_cols:
                cursor.execute(f"ALTER TABLE license_state ADD COLUMN {col_name} {col_def}")

        # Coupons Table
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS coupons (
            code TEXT PRIMARY KEY,
            discount_percent REAL NOT NULL,
            max_uses INTEGER DEFAULT 99999,
            used_count INTEGER DEFAULT 0,
            is_active INTEGER DEFAULT 1,
            notes TEXT DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)

        cursor.execute("SELECT id, plan_name, expires_at, is_vip, max_devices, security_signature FROM license_state WHERE id = 1")
        row = cursor.fetchone()
        now_ts = int(time.time())

        if not row:
            # Default to 14 days free trial signed with current machine fingerprint
            expires_14d = (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%d %H:%M:%S")
            sig = self._compute_security_signature("FREE_TRIAL", expires_14d, 0, 1)
            cursor.execute("""
            INSERT INTO license_state (id, plan_name, status, is_vip, machine_id, security_signature, last_known_ts, expires_at)
            VALUES (1, 'FREE_TRIAL', 'ACTIVE', 0, ?, ?, ?, ?)
            """, (self.machine_id, sig, now_ts, expires_14d))
        elif not row["security_signature"]:
            # Migrate older database to signed state
            plan_name = row["plan_name"] or "FREE_TRIAL"
            expires_at = row["expires_at"]
            if not expires_at:
                expires_at = (datetime.now() + timedelta(days=14)).strftime("%Y-%m-%d %H:%M:%S")
            is_vip = row["is_vip"] or 0
            max_dev = row["max_devices"] or 1
            sig = self._compute_security_signature(plan_name, expires_at, is_vip, max_dev)
            cursor.execute("UPDATE license_state SET machine_id = ?, security_signature = ?, last_known_ts = ?, expires_at = ? WHERE id = 1",
                           (self.machine_id, sig, now_ts, expires_at))

        # Default coupons
        default_coupons = [
            ("ANIL50", 50.0, "Special 50% Owner Discount"),
            ("WEDDING20", 20.0, "Wedding Season 20% Discount"),
            ("PHOTOFLOW10", 10.0, "Welcome 10% Discount"),
            ("VIP100", 100.0, "100% Free VIP Access"),
        ]
        for c in default_coupons:
            cursor.execute("INSERT OR IGNORE INTO coupons (code, discount_percent, notes) VALUES (?, ?, ?)", c)

        conn.commit()
        conn.close()

    def verify_tamper_integrity(self) -> Tuple[bool, str, Dict[str, Any]]:
        """
        Anti-Crack & Anti-Tamper Security Verification:
        1. Checks database signature against embedded cryptographic salt.
        2. Detects computer clock rollback manipulation.
        3. Validates hardware machine ID binding.
        """
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute("""
        SELECT plan_name, license_key, status, is_vip, user_name, user_email, max_devices,
               machine_id, security_signature, last_known_ts, expires_at, activated_at
        FROM license_state WHERE id = 1
        """)
        row = cursor.fetchone()

        if not row:
            conn.close()
            return False, "License state missing", {}

        now_ts = int(time.time())
        last_known_ts = row["last_known_ts"] or 0

        # Anti-Clock Rollback Check:
        # If user changed system clock backwards by more than 1 hour to prevent expiry
        if now_ts < (last_known_ts - 3600):
            conn.close()
            return False, "Clock tampering detected! Please correct your computer's system date and time.", {
                "plan": "LOCKED",
                "status": "TAMPER_DETECTED",
                "is_active": False,
                "days_left": 0
            }

        # Update last known timestamp
        cursor.execute("UPDATE license_state SET last_known_ts = ? WHERE id = 1", (max(now_ts, last_known_ts),))
        conn.commit()
        conn.close()

        plan_name = row["plan_name"]
        is_vip = bool(row["is_vip"])
        expires_at_str = row["expires_at"]
        max_devices = row["max_devices"] or 1
        stored_sig = row["security_signature"]
        stored_machine = row["machine_id"]

        # 1. Cryptographic DB Tamper Check
        expected_sig = self._compute_security_signature(plan_name, expires_at_str, 1 if is_vip else 0, max_devices)
        if stored_sig != expected_sig:
            return False, "Software tampering detected! Database signature invalid.", {
                "plan": "LOCKED",
                "status": "TAMPER_DETECTED",
                "is_active": False,
                "days_left": 0
            }

        # 2. Hardware Machine Binding Check
        if stored_machine and stored_machine != self.machine_id and not is_vip:
            return False, "Hardware license mismatch! License is bound to another device.", {
                "plan": "LOCKED",
                "status": "DEVICE_MISMATCH",
                "is_active": False,
                "days_left": 0
            }

        # 3. Expiry Check
        days_left = 9999
        status = row["status"]
        if expires_at_str:
            try:
                exp_date = datetime.strptime(expires_at_str, "%Y-%m-%d %H:%M:%S")
                delta = exp_date - datetime.now()
                days_left = max(0, delta.days)
                if delta.total_seconds() <= 0:
                    status = "EXPIRED"
                else:
                    status = "ACTIVE"
            except Exception:
                status = "EXPIRED"

        return True, "License valid and secure", {
            "plan": plan_name,
            "status": status,
            "is_active": status == "ACTIVE",
            "is_vip": is_vip,
            "days_left": days_left,
            "expires_at": expires_at_str,
            "user_name": row["user_name"],
            "user_email": row["user_email"],
            "license_key": row["license_key"],
            "machine_id": self.machine_id,
            "max_devices": max_devices,
            "security_verified": True,
            "features": {
                "unlimited_photos": plan_name in ("PRO", "STUDIO", "VIP_LIFETIME"),
                "high_res_export": status == "ACTIVE",
                "indian_skin_tone": True,
                "multi_device": plan_name == "STUDIO",
                "batch_auto_edit": True,
                "all_culling_rules": True
            }
        }

    def get_license_status(self) -> Dict[str, Any]:
        valid, msg, data = self.verify_tamper_integrity()
        if not valid:
            return {
                "plan": "LOCKED",
                "status": "TAMPER_DETECTED",
                "is_active": False,
                "is_vip": False,
                "days_left": 0,
                "machine_id": self.machine_id,
                "tamper_alert": msg,
                "features": {
                    "unlimited_photos": False,
                    "high_res_export": False,
                    "indian_skin_tone": False,
                    "multi_device": False,
                    "batch_auto_edit": False,
                    "all_culling_rules": False
                }
            }
        return data

    def verify_operational_permission(self, action: str = "EXPORT") -> Tuple[bool, str]:
        """
        Called before high-value actions (Batch Export, Batch AI Culling) to enforce anti-tamper.
        """
        status = self.get_license_status()
        if not status.get("is_active"):
            if status.get("status") == "TAMPER_DETECTED":
                return False, "Security Tampering Detected. Please activate a legitimate license."
            return False, "Your Free Trial period has expired. Please upgrade to Pro to continue exporting."
        return True, "Authorized"

    @staticmethod
    def generate_cryptographic_key(plan_type: str, days: int, client_token: str) -> str:
        """
        Creates a mathematically signed license key with embedded HMAC checksum:
        Format: APF-{PLAN}-{DAYS}-{TOKEN}-{CHECKSUM}
        """
        clean_plan = plan_type.upper()
        clean_token = client_token.upper()[:6] or "RETAIL"
        raw_msg = f"{clean_plan}:{days}:{clean_token}"
        sig = hmac.new(_SECURITY_PEPPER, raw_msg.encode("utf-8"), hashlib.sha256).hexdigest()[:8].upper()
        return f"APF-{clean_plan}-{days}-{clean_token}-{sig}"

    @staticmethod
    def verify_cryptographic_key(key: str) -> Tuple[bool, str, int, str]:
        """
        Verifies the mathematical signature of a license key.
        Cracked or random keys will fail here.
        """
        clean_key = (key or "").strip().upper()
        parts = clean_key.split("-")
        if len(parts) < 5 or parts[0] != "APF":
            return False, "", 0, "Invalid key format"

        plan = parts[1]
        try:
            days = int(parts[2])
        except ValueError:
            return False, "", 0, "Invalid key duration"

        token = parts[3]
        sig = parts[4]

        # Verify mathematical checksum
        raw_msg = f"{plan}:{days}:{token}"
        expected_sig = hmac.new(_SECURITY_PEPPER, raw_msg.encode("utf-8"), hashlib.sha256).hexdigest()[:8].upper()

        if sig != expected_sig:
            return False, "", 0, "License Key Checksum Signature Failed (Counterfeit/Forged Key)"

        return True, plan, days, "Valid"

    def activate_key(self, key: str, user_name: str = "", user_email: str = "") -> Tuple[bool, str, Dict[str, Any]]:
        clean_key = (key or "").strip().upper()
        if not clean_key:
            return False, "Please enter a valid license key.", {}

        # 1. VIP Free Master Keys authorized by Anil Sharma
        if clean_key in ("ANIL-FREE-LIFETIME-VIP", "VIP-ANIL-SHARMA-LIFETIME", "ANIL786-LIFETIME", "ANIL-FREE-LIFETIME"):
            return self._set_secure_license(
                plan_name="VIP_LIFETIME",
                license_key=clean_key,
                is_vip=1,
                days=None,
                user_name=user_name or "VIP Partner",
                user_email=user_email,
                max_devices=3
            )

        # 2. Mathematically Signed Cryptographic Keys (APF-{PLAN}-{DAYS}-{TOKEN}-{CHECKSUM})
        valid, plan, days, msg = self.verify_cryptographic_key(clean_key)
        if valid:
            plan_name = "STUDIO" if plan == "STUDIO" else "PRO"
            max_devices = 3 if plan_name == "STUDIO" else 1
            return self._set_secure_license(
                plan_name=plan_name,
                license_key=clean_key,
                is_vip=0,
                days=days,
                user_name=user_name,
                user_email=user_email,
                max_devices=max_devices
            )

        return False, "Invalid or unauthorized license key. Signature verification failed.", {}

    def _set_secure_license(self, plan_name: str, license_key: str, is_vip: int, days: Optional[int], user_name: str, user_email: str, max_devices: int) -> Tuple[bool, str, Dict[str, Any]]:
        """
        Cryptographically signs and stores license record with hardware machine binding.
        """
        expires_at_str = None
        if days is not None and days > 0:
            expires_at_str = (datetime.now() + timedelta(days=days)).strftime("%Y-%m-%d %H:%M:%S")

        activated_at_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        now_ts = int(time.time())

        # Generate tamper-proof cryptographic signature
        sig = self._compute_security_signature(plan_name, expires_at_str, is_vip, max_devices)

        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute("""
        UPDATE license_state SET
            plan_name = ?,
            license_key = ?,
            status = 'ACTIVE',
            is_vip = ?,
            user_name = ?,
            user_email = ?,
            max_devices = ?,
            machine_id = ?,
            security_signature = ?,
            last_known_ts = ?,
            expires_at = ?,
            activated_at = ?
        WHERE id = 1
        """, (plan_name, license_key, is_vip, user_name, user_email, max_devices, self.machine_id, sig, now_ts, expires_at_str, activated_at_str))
        conn.commit()
        conn.close()

        status_data = self.get_license_status()
        return True, f"Successfully activated {plan_name} plan! (Hardware bound & Cryptographically Verified)", status_data

    # Backwards compatibility alias
    _set_license = _set_secure_license

    def admin_grant_free_access(self, admin_pin: str, plan_type: str = "VIP_LIFETIME", client_name: str = "") -> Tuple[bool, str, Dict[str, Any]]:
        if admin_pin != ADMIN_MASTER_PIN:
            return False, "Invalid Admin Master PIN", {}
        
        plan = "VIP_LIFETIME" if "VIP" in plan_type.upper() else plan_type.upper()
        days = None if "VIP" in plan else 365
        key = f"APF-VIP-ANIL-{uuid.uuid4().hex[:8].upper()}"
        return self._set_secure_license(
            plan_name=plan,
            license_key=key,
            is_vip=1 if "VIP" in plan else 0,
            days=days,
            user_name=client_name or "VIP Complimentary User",
            user_email="",
            max_devices=3
        )

    def admin_create_coupon(self, admin_pin: str, code: str, discount_pct: float, notes: str = "") -> Tuple[bool, str]:
        if admin_pin != ADMIN_MASTER_PIN:
            return False, "Invalid Admin Master PIN"
        
        code_clean = (code or "").strip().upper()
        if not code_clean:
            return False, "Coupon code cannot be empty"
        
        conn = get_connection()
        c = conn.cursor()
        c.execute("""
        INSERT INTO coupons (code, discount_percent, notes, is_active)
        VALUES (?, ?, ?, 1)
        ON CONFLICT(code) DO UPDATE SET discount_percent = excluded.discount_percent, notes = excluded.notes, is_active = 1
        """, (code_clean, float(discount_pct), notes))
        conn.commit()
        conn.close()
        return True, f"Coupon {code_clean} ({discount_pct}%) created successfully"

    def admin_generate_key(self, admin_pin: str, plan_type: str = "PRO", days: int = 365, client_name: str = "") -> Tuple[bool, str, str]:
        if admin_pin != ADMIN_MASTER_PIN:
            return False, "Invalid Admin Master PIN", ""
        
        token = (client_name.upper().replace(" ", "")[:6]) or uuid.uuid4().hex[:6].upper()
        key = self.generate_cryptographic_key(plan_type, days, token)
        return True, "Key generated successfully", key

    def verify_coupon(self, code: str, plan_id: str, billing_cycle: str, currency: str = "INR") -> Dict[str, Any]:
        code_clean = (code or "").strip().upper()
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT code, discount_percent, is_active, notes FROM coupons WHERE UPPER(code) = ?", (code_clean,))
        row = cursor.fetchone()
        conn.close()

        if not row or not row["is_active"]:
            return {"valid": False, "message": "Invalid or expired referral/coupon code"}

        discount_pct = float(row["discount_percent"])
        currency = currency.upper() if currency in ("INR", "USD") else "INR"
        plan_id = plan_id.upper()
        cycle = billing_cycle.lower()

        prices = PRICING_CATALOG.get(currency, PRICING_CATALOG["INR"])
        plan_pricing = prices.get(plan_id, prices["PRO"])
        base_price = plan_pricing.get(cycle, plan_pricing.get("yearly", 11999))

        discount_amount = round((base_price * discount_pct) / 100.0)
        final_price = max(0, base_price - discount_amount)

        return {
            "valid": True,
            "code": row["code"],
            "discount_percent": discount_pct,
            "original_price": base_price,
            "discount_amount": discount_amount,
            "final_price": final_price,
            "currency": currency,
            "notes": row["notes"],
            "message": f"{int(discount_pct)}% referral discount successfully applied!"
        }
