<?php
// Generated by scripts/build_license_server.py — never commit the real config.php.
if (!defined('APF_SERVER')) { http_response_code(403); exit; }
define('APF_PUBLIC_KEY_B64', '__PUBLIC_KEY__');
define('APF_SECRET_KEY_B64', '__SECRET_KEY__');   // Ed25519 signing key: only on this server
define('APF_SETUP_CODE', '__SETUP_CODE__');       // needed once to create the admin account
define('APF_DATA_DIR', '');                       // blank = automatic (outside public_html when possible)
